=== Noorunnisa7/xml-and-json-learning/class3/book.dtd
<!ELEMENT bookstore (book+)>
<!ELEMENT book (name,price,version)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ATTLIST book id CDATA #REQUIRED>
<!ATTLIST book category CDATA #IMPLIED>
<!ATTLIST name title CDATA #FIXED "HELLO">

=== Noorunnisa7/xml-and-json-learning/class3/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "book.dtd">
<bookstore>
    <book id="1">
         <name title="HELLO">Ms office</name>
         <price>$3</price>
         <version>2021</version>
    </book>
    <book id="2">
         <name title="HELLO">Javacript</name>
          <price>$30</price>
         <version>ES6</version>
        </book>
    <book id="3">
         <name>XML</name>
         <price>$1</price>
         <version>ES6</version>
    </book>
    <book id="4">
         <name>HTML</name>
         <price>$5</price>
         <version>5</version>
    </book>
    <book id="5">
         <name>Ms office</name>
         <price>$3</price>
         <version>2021</version>
    </book>
</bookstore>
